spring:
  profiles:
    active: dev
  application:
    name: BaniraKanri
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/banira_data.db
    username:
    password:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
      pool-name: BaniraHikari
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      mode: never

shiro:
  ws:
    access-token:
    client:
      enable: true
      url: ws://127.0.0.1:8080
mybatis-plus:
  global-config:
    banner: false
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:xin/vanilla/**/mybatis-*.xml
  type-aliases-package: xin.vanilla.**.domain,xin.vanilla.**.entity,xin.vanilla.**.po
